# Generated by Django 3.0 on 2022-02-05 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PoseAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('output', models.ImageField(blank=True, null=True, upload_to='')),
                ('analysis', models.TextField(blank=True, null=True)),
                ('pose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pose_analyser.Pose')),
            ],
        ),
    ]
